services:
  postgres:
    image: postgres:16-alpine
    container_name: split_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: split_user
      POSTGRES_PASSWORD: split_password
      POSTGRES_DB: split_db
    ports:
      - "5432:5432"
    volumes:
      - split_postgres_data:/var/lib/postgresql/data

volumes:
  split_postgres_data:
